# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Delilah's Passport
email: delilahflexas@gmail.com

# Where can people find your site?
url: "http://delilahspassport.com"
url-pretty: "http://delilahspassport.com"

# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter: https://www.instagram.com/dflexas/
facebook:
google:
instagram: https://www.instagram.com/dflexas/

author: Delilah Flexas
authorBio: hello world
